import { NextAuthOptions } from "next-auth";
import CredentialsProvider from "next-auth/providers/credentials";
import admin from "firebase-admin";

// Set emulator environment variables at module level BEFORE any Admin SDK initialization
// According to Firebase docs: https://firebase.google.com/docs/emulator-suite/connect_auth
// The Admin SDK automatically connects to the emulator when FIREBASE_AUTH_EMULATOR_HOST is set
if (process.env.USE_FIREBASE_EMULATOR === "true") {
  if (!process.env.FIREBASE_AUTH_EMULATOR_HOST) {
    process.env.FIREBASE_AUTH_EMULATOR_HOST = "localhost:9099";
  }
  if (!process.env.FIRESTORE_EMULATOR_HOST) {
    process.env.FIRESTORE_EMULATOR_HOST = "localhost:8080";
  }
  // Log to verify emulator configuration (only in development)
  if (process.env.NODE_ENV !== "production") {
    console.log("✅ Server-side: Firebase Admin SDK configured for EMULATOR");
    console.log(
      "   FIREBASE_AUTH_EMULATOR_HOST:",
      process.env.FIREBASE_AUTH_EMULATOR_HOST,
    );
    console.log(
      "   FIRESTORE_EMULATOR_HOST:",
      process.env.FIRESTORE_EMULATOR_HOST,
    );
  }
} else if (process.env.NODE_ENV !== "production") {
  console.warn(
    "⚠️  Server-side: Firebase Admin SDK NOT using emulator. USE_FIREBASE_EMULATOR:",
    process.env.USE_FIREBASE_EMULATOR,
  );
}

// Initialize Firebase Admin SDK for token verification
let adminInitialized = false;

function initializeAdmin() {
  if (adminInitialized || admin.apps.length > 0) {
    return true;
  }

  try {
    // When using emulator, ALWAYS prioritize emulator initialization
    // This ensures the Admin SDK uses the emulator's project ID ("demo-test")
    // which matches the tokens generated by the emulator
    // See: https://firebase.google.com/docs/emulator-suite/connect_auth#web
    if (process.env.USE_FIREBASE_EMULATOR === "true") {
      // For emulator, Admin SDK can be initialized without credentials
      // The emulator environment variables set at module level will make it connect to the emulator
      // According to Firebase docs, Admin SDK automatically uses emulator when FIREBASE_AUTH_EMULATOR_HOST is set
      // CRITICAL: Use "demo-test" as project ID to match the emulator's project ID
      // This ensures token verification works correctly (tokens have aud: "demo-test")
      try {
        admin.initializeApp({
          projectId: "demo-test", // Must match emulator's project ID
        });
        adminInitialized = true;
        if (process.env.NODE_ENV !== "production") {
          console.log(
            "✅ Firebase Admin SDK initialized for EMULATOR with projectId: demo-test",
          );
          console.log(
            "   FIREBASE_AUTH_EMULATOR_HOST:",
            process.env.FIREBASE_AUTH_EMULATOR_HOST,
          );
        }
        return true;
      } catch (emulatorError) {
        console.error(
          "Firebase Admin emulator initialization error:",
          emulatorError,
        );
        if (emulatorError instanceof Error) {
          console.error("Error message:", emulatorError.message);
        }
        return false;
      }
    }

    // For production, try to initialize with service account credentials
    const serviceAccount = process.env.FIREBASE_SERVICE_ACCOUNT
      ? JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT)
      : null;

    if (serviceAccount) {
      admin.initializeApp({
        credential: admin.credential.cert(serviceAccount),
      });
      adminInitialized = true;
      return true;
    } else {
      // Fallback: try to use default credentials (for Firebase hosting/Cloud Run)
      try {
        admin.initializeApp({
          credential: admin.credential.applicationDefault(),
        });
        adminInitialized = true;
        return true;
      } catch (defaultError) {
        console.error("Firebase Admin initialization error:", defaultError);
        return false;
      }
    }
  } catch (error) {
    console.error("Firebase Admin initialization error:", error);
    return false;
  }
}

export const authOptions: NextAuthOptions = {
  providers: [
    CredentialsProvider({
      name: "Firebase",
      credentials: {
        idToken: { label: "ID Token", type: "text" },
      },
      async authorize(credentials) {
        if (!credentials?.idToken) {
          return null;
        }

        try {
          // Initialize Admin SDK if not already initialized
          if (!initializeAdmin()) {
            console.error("Failed to initialize Firebase Admin SDK");
            return null;
          }

          // Verify the Firebase ID token using Admin SDK
          // This works with both production and emulator (when env vars are set)
          const decodedToken = await admin.auth().verifyIdToken(
            credentials.idToken,
          );

          if (decodedToken) {
            return {
              id: decodedToken.uid,
              email: decodedToken.email || null,
              name: decodedToken.name || null,
              firebaseIdToken: credentials.idToken, // Store the ID token
            };
          }
          return null;
        } catch (error) {
          console.error("Auth error:", error);
          // Log more details for debugging
          if (error instanceof Error) {
            console.error("Auth error message:", error.message);
            console.error("Auth error stack:", error.stack);
          }
          // Log emulator configuration
          if (process.env.USE_FIREBASE_EMULATOR === "true") {
            console.error("Emulator mode enabled");
            console.error(
              "FIREBASE_AUTH_EMULATOR_HOST:",
              process.env.FIREBASE_AUTH_EMULATOR_HOST,
            );
            console.error("Admin apps initialized:", admin.apps.length);
          }
          return null;
        }
      },
    }),
  ],
  callbacks: {
    async jwt({ token, user }) {
      if (user) {
        token.id = user.id;
        token.email = user.email;
        // Store the Firebase ID token from user object
        if (
          "firebaseIdToken" in user && typeof user.firebaseIdToken === "string"
        ) {
          token.firebaseIdToken = user.firebaseIdToken;
        }
      }
      return token;
    },
    async session({ session, token }) {
      if (session.user) {
        session.user.id = token.id as string;
        // Include Firebase ID token in session for client-side use
        session.firebaseIdToken = token.firebaseIdToken;
      }
      return session;
    },
  },
  pages: {
    signIn: "/login",
  },
  session: {
    strategy: "jwt",
  },
  secret: process.env.AUTH_SECRET,
};
