import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/auth";
import admin from "firebase-admin";

// Set emulator environment variables at module level BEFORE any Admin SDK initialization
// According to Firebase docs: https://firebase.google.com/docs/emulator-suite/connect_auth
// The Admin SDK automatically connects to the emulator when FIREBASE_AUTH_EMULATOR_HOST is set
if (process.env.USE_FIREBASE_EMULATOR === "true") {
  if (!process.env.FIREBASE_AUTH_EMULATOR_HOST) {
    process.env.FIREBASE_AUTH_EMULATOR_HOST = "localhost:9099";
  }
  if (!process.env.FIRESTORE_EMULATOR_HOST) {
    process.env.FIRESTORE_EMULATOR_HOST = "localhost:8080";
  }
}

// Initialize Firebase Admin SDK
let adminInitialized = false;

function initializeAdmin() {
  if (adminInitialized || admin.apps.length > 0) {
    return true;
  }

  try {
    // When using emulator, ALWAYS prioritize emulator initialization
    // This ensures the Admin SDK uses the emulator's project ID ("demo-test")
    // which matches the tokens generated by the emulator
    // See: https://firebase.google.com/docs/emulator-suite/connect_auth#web
    if (process.env.USE_FIREBASE_EMULATOR === "true") {
      // For emulator, Admin SDK can be initialized without credentials
      // The emulator environment variables set at module level will make it connect to the emulator
      // According to Firebase docs, Admin SDK automatically uses emulator when FIREBASE_AUTH_EMULATOR_HOST is set
      // CRITICAL: Use "demo-test" as project ID to match the emulator's project ID
      // This ensures token verification works correctly (tokens have aud: "demo-test")
      try {
        admin.initializeApp({
          projectId: "demo-test", // Must match emulator's project ID
        });
        adminInitialized = true;
        if (process.env.NODE_ENV !== "production") {
          console.log(
            "✅ Firebase Admin SDK initialized for EMULATOR with projectId: demo-test",
          );
          console.log(
            "   FIREBASE_AUTH_EMULATOR_HOST:",
            process.env.FIREBASE_AUTH_EMULATOR_HOST,
          );
        }
        return true;
      } catch (emulatorError) {
        console.error(
          "Firebase Admin emulator initialization error:",
          emulatorError,
        );
        if (emulatorError instanceof Error) {
          console.error("Error message:", emulatorError.message);
        }
        return false;
      }
    }

    // For production, try to initialize with service account credentials
    // You can set this via environment variable (FIREBASE_SERVICE_ACCOUNT as JSON string)
    const serviceAccount = process.env.FIREBASE_SERVICE_ACCOUNT
      ? JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT)
      : null;

    if (serviceAccount) {
      admin.initializeApp({
        credential: admin.credential.cert(serviceAccount),
      });
      adminInitialized = true;
      return true;
    } else {
      // Fallback: try to use default credentials (for Firebase hosting/Cloud Run)
      try {
        admin.initializeApp({
          credential: admin.credential.applicationDefault(),
        });
        adminInitialized = true;
        return true;
      } catch (defaultError) {
        console.error("Firebase Admin initialization error:", defaultError);
        return false;
      }
    }
  } catch (error) {
    console.error("Firebase Admin initialization error:", error);
    return false;
  }
}

export async function POST() {
  try {
    // Initialize Firebase Admin SDK
    if (!initializeAdmin()) {
      return NextResponse.json(
        {
          error:
            "Firebase Admin SDK not initialized. Please set FIREBASE_SERVICE_ACCOUNT environment variable.",
        },
        { status: 500 },
      );
    }

    // Get the NextAuth session
    const session = await getServerSession(authOptions);

    if (!session?.firebaseIdToken) {
      return NextResponse.json(
        { error: "No Firebase ID token in session" },
        { status: 401 },
      );
    }

    // Verify the ID token
    const decodedToken = await admin.auth().verifyIdToken(
      session.firebaseIdToken,
    );

    // Create a custom token
    const customToken = await admin.auth().createCustomToken(decodedToken.uid);

    return NextResponse.json({ customToken });
  } catch (error) {
    console.error("Error creating custom token:", error);
    const errorMessage = error instanceof Error
      ? error.message
      : "Failed to create custom token";
    return NextResponse.json({ error: errorMessage }, { status: 500 });
  }
}
